namespace FAIL.Exceptions;
internal class ContinueException : Exception
{
}
